.\" Man page for minidlna.conf
.\"
.\" This man page is based on the comments in the default configuration file
.\" shipped with the minidlna source. Consequently, it is licensed under the
.\" GPLv2.
.\"
.\" Copyright (C) 2009 Justin Maggard <jmaggard@users.sourceforge.net>
.\" Copyright (C) 2010-2011 Benoît Knecht <benoit.knecht@fsfe.org>
.\"
.\"    This package is free software; you can redistribute it and/or modify
.\"    it under the terms of the GNU General Public License version 2 as
.\"    published by the Free Software Foundation.
.\"
.\"    This package is distributed in the hope that it will be useful,
.\"    but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"    GNU General Public License for more details.
.\"
.\"    You should have received a copy of the GNU General Public License
.\"    along with this program. If not, see <http://www.gnu.org/licenses/>
.\"
.\" On Debian systems, the complete text of the GNU General
.\" Public License version 2 can be found in "/usr/share/common-licenses/GPL-2".
.Dd July 21, 2012
.Dt MINIDLNA.CONF \&5 "File Formats Manual"
.Os Debian
.Sh NAME
.Nm minidlna.conf
.Nd MiniDLNA server configuration file
.Sh SYNOPSIS
.Nm /etc/minidlna.conf
.Sh DESCRIPTION
.Xr minidlna 1
reads configuration options from the system-wide configuration file
.Pa /etc/minidlna.conf ,
or the file specified with
.Fl f
on the command line. The file contains keyword-argument pairs, one per line.
Lines starting with
.Ql #
and empty lines are interpreted as comments.
.Pp
The possible
keywords and their meanings are as follows:
.Bl -tag -width Ds
.It Cm album_art_names
List of filenames to check for when searching for album art cache, separated by
forward slashes
.Pq Ql / .
This option can be specified more than once.
.It Cm db_dir
Path to the directory
.Nm minidlna
should use to store its database and album art cache. Uses
.Pa /var/lib/minidlna
by default.
.It Cm enable_tivo
Set to
.Dq yes
to enable support for streaming JPEG and mp3 files to a TiVo supporting HMO.
Set to
.Dq no
otherwise.
.It Cm friendly_name
Customize the name that the
.Nm minidlna
server sends to clients. Defaults to
.Dq hostname:\ username .
.It Cm inotify
Set to
.Dq yes
to enable inotify monitoring of the files under
.Cm media_dir
to automatically discover new files. Set to
.Dq no
to disable inotify.
.It Cm listening_ip
IPv4 address
.Nm minidlna
should listen on
.Pq e.g. Dq 198.51.100.1/24 .
If omitted, the mask defaults to /24. This option can be specified more than
once. If unspecified or empty,
.Nm minidlna
binds to the network interfaces given in
.Cm network_interface ;
if it is also unspecified or empty, it binds to all the valid network
interfaces
.Pq except loopback .
.It Cm log_dir
Path to the directory where the log file should be stored. Defaults to
.Pa /var/log .
.It Cm log_level
Defines the type of messages that should be logged, and down to which level of
importance they should be considered.
.Pp
The possible types are
.Dq artwork ,
.Dq database ,
.Dq general ,
.Dq http ,
.Dq inotify ,
.Dq metadata ,
.Dq scanner ,
.Dq ssdp
and
.Dq tivo .
.Pp
The levels are
.Dq off ,
.Dq fatal ,
.Dq error ,
.Dq warn ,
.Dq info
and
.Dq debug ,
listed here in order of decreasing importance.
.Dq off
turns off logging messages entirely,
.Dq fatal
logs the most critical messages only, and so on down to
.Dq debug
that logs every single messages.
.Pp
The types are comma-separated, followed by an equal sign
.Pq Ql = ,
followed by a level that applies to the preceding types. This can be repeated,
separating each of these constructs with a comma.
.Pp
Defaults to
.Dq general,\:artwork,\:database,\:inotify,\:scanner,\:metadata,\:http,\:\
ssdp,\:tivo=warn
which logs every type of message at the
.Dq warn
level.
.It Cm media_dir
Path to the directory containing the media files the
.Nm minidlna
server should share. Use this option several times if you have more than one
directory to share. To restrict a path to one specific media type, you can use
the following syntax: the letter
.Ql A ,
.Ql V
or
.Ql P ,
followed by a comma
.Pq Ql \&,
followed by the path. The meaning of the first letter is as follows:
.Bl -bullet -offset indent -compact
.It
.Ql A
for audio files;
.It
.Ql V
for video files;
.It
.Ql P
for image files.
.El
For example, if you want to include only video files located under the
.Pa /opt/media/videos
directory, you would use
.Cm media_dir=V,/opt/media/videos .
.Pp
After making changes to this option, you need to rebuild the database.
If you use an init script to start/stop
.Nm minidlna,
then you should run
.Pq as root
.Ic service
.Cm minidlna
.Cm force-reload .
Otherwise, just add
.Fl R
to your usual
.Nm minidlna
command line
.Po
.Ic minidlna
.Op ...
.Fl R
.Pc .
.It Cm minissdpdsocket
Path to the MiniSSDPd socket, if you want to use
.Nm minidlna
together with MiniSSDPd. Defaults to
.Pa /run/minissdpd.sock .
.It Cm model_name
Set the model name reported to clients.
Defaults to
.Dq Windows Media Connect compatible (MiniDLNA) .
.It Cm model_number
Set the model number reported to clients. Defaults to the version number of
.Nm minidlna .
.It Cm network_interface
Network interface(s) to bind to
.Pq e.g. eth0 ,
comma delimited. This option can be specified more than once. If unspecified or empty,
.Nm minidlna
binds to the IPs given in
.Cm listening_ip ;
if it is also unspecified or empty, it binds to all the valid network
interfaces
.Pq except loopback .
.It Cm notify_interval
Set the notify interval, in seconds. The default is 895 seconds.
.It Cm port
Port number for HTTP traffic
.Pq descriptions, SOAP, media transfe .
This option is mandatory, unless the port number is specified on the
command-line using
.Fl p Pq see Xr minidlna 1 .
.It Cm presentation_url
Define the URL presented to clients
.Pq e.g. Dq http://example.com:80 .
The default is
.Ql / .
.It Cm root_container
Use a different container as the root of the tree exposed to clients. The
possible values 
.Bl -bullet -offset indent -compact
.It
.Ql \&.
to use the standard container (this is the default);
.It
.Ql B
to use the
.Dq Browse Directory
container;
.It
.Ql M
to use the
.Dq Music
container;
.It
.Ql V
to use the
.Dq Video
container;
.It
.Ql P
to use the
.Dq Pictures
container.
.El
If you specify
.Ql B
and the client device is audio only, then
.Dq Music/Folders
will be used as the root container.
.It Cm serial
Set the serial number reported to clients. Defaults to
.Dq 00000000 .
.It Cm strict_dlna
Set to
.Dq yes
to strictly adhere to DLNA standards. This will allow server-side downscaling
of very large JPEG images, which may hurt JPEG serving performance on (at
least) Sony DLNA products. Set to
.Dq no
otherwise.
.El
.Sh FILES
.Bl -tag -width Ds
.It Pa /etc/minidlna.conf
System-wide default configuration file.
.El
.Sh SEE ALSO
.Xr minidlna 1
